### ISSUE TITLE
No instructions for compiling source code

### ISSUE THREAD

**Issue by Emily82** [Bombe/jSite#5]
Hi, i downloaded the last release and there is no readme for compiling source code.
How to compile?

**Comment by jlxip** [comment]
It's quite easy indeed. As it's a project in Java, just install an IDE for it (I highly recommend **Eclipse**).
Once Eclipse is running (and the repo is cloned) go to _File > Import > Existing Projects into Workspace_.
Paste the directory of your local copy of the repo, and make sure that the project jSite is ticked; then, click _Finish_.
By now, the project should be included in your workspace without any errors.
Finally, right click the project (listed on the left) and click _Export_. Select _Runnable JAR file_, and in _Launch configuration_ make sure that It's _Main - jSite_. Click _Browse..._ in order to change the output of the compiled jar, and click _Finish_. Maybe a warning appears, just click OK.
That's it, you should have the compiled jar in the directory of your chose.

**Comment by Emily82** [comment]
Isn't a way to compile it just from terminal?

**Comment by jlxip** [comment]
- Install **Apache Ant**.
- In the local repo directory, download these files:
-- https://maven.pterodactylus.net/net/pterodactylus/utils/0.13/utils-0.13.jar
-- https://pastebin.com/raw/CH9D5JyF
(Save this last file as **build.xml**)
- Run: _ant -buildfile build.xml_

**Comment by Emily82** [comment]
I had to create manually directories: target and target/classes

After that building is sucessful but executing output.jar with:

java -jar output.jar

i got this error (i translate it in english because its in italian) :

Error: cannot find or load main class de.todesbaum.jsite.main.Main

**Comment by Bombe** [comment]
Hold on, hold on.

a) if you’re trying to build master you need Maven installed. Get it from https://maven.apache.org/, call `mvn clean package`.
b) if you’re trying to build `next`, the Gradle wrapper is supplied. Call `./gradlew clean build fatJar` to create an executable JAR file in the `build/libs` directory.

**Comment by Emily82** [comment]
Thanks it works.
It seems that only jSite-0.13-jar-with-dependencies.jar is working, is it all ok?

**Comment by Bombe** [comment]
Yes, that’s perfectly okay. Keep it right there, copy it where you want, it should work from everywhere. :)
