### ISSUE TITLE
The MIME detection is inaccurate

### ISSUE THREAD

**Issue by Mosesofmason** [Bombe/jSite#7]
In my case, the MIME detection for *.jpg images is incorrect for some reason. Certain images are being identified as application/octet-stream instead of image/jpeg, and I have to manually change them one by one.

I would greatly appreciate it if there could be an enhancement in the accuracy of the MIME detection. Additionally, the inclusion of a batch change option would be highly beneficial for a smoother process.

jSite version 0.14
JDK version: 21.0.1

**Comment by Bombe** [comment]
I just took a look at how I’m selecting default MIME types for files, and the only thing that is being used to select the default MIME type is the file’s extension. In order to be recognized as “image/jpeg,” the file needs to end in “.jpeg”, “.jpg”, or “.jpe”. Also, bear in mind that the extension is case-sensitive, so “IMAGE.JPG” will not be recognized as a JPEG image.

Does that help?

**Comment by Mosesofmason** [comment]
Yes, upon rechecking, the file extensions of the problematic files indeed have uppercase letters.

**Comment by Bombe** [comment]
I’m a bit on the fence whether I should change anything here but as I can find arguments for both “do it” and “don’t do it” I err on the side of laziness and will be closing this issue. 😄
